from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Optional

import torch

from config import DataConfig, TrainConfig
from data.tokenizer_custom import CustomDeltaTokenizer
from model.variant_c import VariantCConfig, VariantCModel
from training.ablation_runner import (
    _build_dataloaders,
    _load_pretokenized_manifest,
    _run_variant,
    _set_global_seed,
    _train_val_split,
)
from utils.logging_utils import get_project_logger


LOGGER = get_project_logger()


C_PRESETS: Dict[str, Dict[str, int]] = {
    "40m": {
        "d_model": 512,
        "n_layers": 12,
        "num_attention_heads": 8,
        "ffn_expansion": 4,
        "target_params": 40_000_000,
    },
    "80m": {
        "d_model": 640,
        "n_layers": 16,
        "num_attention_heads": 8,
        "ffn_expansion": 4,
        "target_params": 80_000_000,
    },
}


def _resolve_divisible_heads(width: int, requested_heads: int) -> int:
    heads = max(1, min(int(requested_heads), int(width)))
    while heads > 1 and (int(width) % heads) != 0:
        heads -= 1
    return max(1, heads)


def _resolve_resume_checkpoint_arg(
    raw_value: str,
    default_checkpoint_dir: Path,
) -> Optional[Path]:
    value = str(raw_value).strip()
    if not value:
        return None

    def _pick_from_dir(dir_path: Path) -> Optional[Path]:
        candidates = [
            dir_path / "latest_state.pt",
            dir_path / "latest.safetensors",
            dir_path / "best_state.pt",
            dir_path / "best.safetensors",
        ]
        return next((p for p in candidates if p.exists()), None)

    if value.lower() in {"auto", "latest"}:
        found = _pick_from_dir(default_checkpoint_dir)
        if found is None:
            raise FileNotFoundError(
                "No checkpoint found for auto/latest resume under "
                f"{default_checkpoint_dir.resolve()}"
            )
        return found

    candidate = Path(value).expanduser()
    if candidate.is_file():
        return candidate
    if candidate.is_dir():
        found = _pick_from_dir(candidate)
        if found is None:
            raise FileNotFoundError(
                "No checkpoint files found in directory "
                f"{candidate.resolve()} (expected latest_state.pt/latest.safetensors)."
            )
        return found

    raise FileNotFoundError(
        f"resume_from_checkpoint not found: {candidate.resolve()}"
    )


def _build_train_config(
    *,
    args: argparse.Namespace,
    checkpoint_dir: Path,
    warmup_steps: int,
) -> TrainConfig:
    cfg = TrainConfig(
        batch_size=int(args.batch_size),
        grad_accumulation_steps=int(args.grad_accumulation_steps),
        learning_rate=float(args.learning_rate),
        lr_schedule="cosine",
        min_lr_ratio=float(args.min_lr_ratio),
        weight_decay=float(args.weight_decay),
        label_smoothing=float(args.label_smoothing),
        max_epochs=int(args.epochs),
        warmup_steps=int(max(1, warmup_steps)),
        max_grad_norm=float(args.max_grad_norm),
        save_every_n_epochs=int(max(1, args.save_every_n_epochs)),
        keep_every_n_epochs=int(max(1, args.keep_every_n_epochs)),
        max_checkpoints=int(max(1, args.max_checkpoints)),
        checkpoint_dir=str(checkpoint_dir),
        use_wandb=False,
        seed=int(args.seed),
        device="auto",
        val_generation_check=False,
    )
    setattr(cfg, "_force_num_workers", int(max(0, args.num_workers)))
    setattr(cfg, "_enable_data_parallel", not bool(args.disable_data_parallel))
    setattr(cfg, "_log_every_n_steps", int(max(1, args.log_every_n_steps)))
    return cfg


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train Transformer Variant C with curated sub-100M presets (40M or 80M) "
            "on pre-tokenized NPZ data. Defaults are tuned for early quality validation "
            "on a 15k-piece subset."
        )
    )
    parser.add_argument(
        "--size_preset",
        type=str,
        choices=sorted(C_PRESETS.keys()),
        default="80m",
        help="Model-size preset.",
    )
    parser.add_argument(
        "--pretokenized_manifest",
        type=str,
        required=True,
        help="Path to manifest.json generated by scripts/tokenize_godzilla_local.py",
    )
    parser.add_argument(
        "--pretokenized_root",
        type=str,
        default="",
        help="Optional root to resolve relative npz paths from the manifest.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="",
        help=(
            "Output directory. If empty, uses outputs/variant_c_<size_preset>."
        ),
    )
    parser.add_argument(
        "--resume_from_checkpoint",
        type=str,
        default="",
        help=(
            "Checkpoint file (.pt/.safetensors), checkpoint directory, or auto/latest "
            "to resume from latest checkpoint in this run's checkpoint directory."
        ),
    )
    parser.add_argument(
        "--resume_mode",
        type=str,
        choices=["remaining", "additional"],
        default="remaining",
        help=(
            "Resume behavior: remaining treats --epochs as total target epoch count; "
            "additional treats --epochs as extra epochs after resume."
        ),
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--seed_length", type=int, default=512)
    parser.add_argument("--continuation_length", type=int, default=1536)
    parser.add_argument("--max_sequence_length", type=int, default=2048)
    parser.add_argument(
        "--max_pieces",
        type=int,
        default=15000,
        help="Cap number of pieces loaded from manifest (default: 15000).",
    )

    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--grad_accumulation_steps", type=int, default=16)
    parser.add_argument("--learning_rate", type=float, default=2e-4)
    parser.add_argument("--min_lr_ratio", type=float, default=0.1)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--label_smoothing", type=float, default=0.1)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument(
        "--warmup_steps",
        type=int,
        default=0,
        help="If > 0, overrides warmup_ratio-based warmup.",
    )
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--log_every_n_steps", type=int, default=20)
    parser.add_argument("--save_every_n_epochs", type=int, default=5)
    parser.add_argument("--keep_every_n_epochs", type=int, default=10)
    parser.add_argument("--max_checkpoints", type=int, default=8)

    parser.add_argument(
        "--disable_data_parallel",
        action="store_true",
        help="Disable DataParallel (default uses DataParallel when multiple GPUs are available).",
    )

    parser.add_argument(
        "--seed_midi",
        type=str,
        default="",
        help="Optional seed MIDI for one post-training continuation export.",
    )
    parser.add_argument(
        "--generation_max_new_tokens",
        type=int,
        default=8192,
        help="Max tokens for optional post-train sample generation.",
    )
    parser.add_argument(
        "--generation_continuation_seconds",
        type=float,
        default=120.0,
        help="Target continuation length in seconds for optional sample export.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if int(args.seed_length) <= 0 or int(args.continuation_length) <= 0:
        raise ValueError("seed_length and continuation_length must be > 0")
    if int(args.max_sequence_length) <= 0:
        raise ValueError("max_sequence_length must be > 0")
    if int(args.seed_length) + int(args.continuation_length) != int(
        args.max_sequence_length
    ):
        raise ValueError(
            "seed_length + continuation_length must equal max_sequence_length "
            f"(got {int(args.seed_length) + int(args.continuation_length)} vs "
            f"{int(args.max_sequence_length)})"
        )

    preset = dict(C_PRESETS[str(args.size_preset).lower()])
    d_model = int(preset["d_model"])
    n_layers = int(preset["n_layers"])
    attn_heads = _resolve_divisible_heads(d_model, int(preset["num_attention_heads"]))
    ffn_expansion = int(preset["ffn_expansion"])

    default_output_dir = Path("outputs") / f"variant_c_{str(args.size_preset).lower()}"
    output_dir = (
        Path(str(args.output_dir)).expanduser()
        if str(args.output_dir).strip()
        else default_output_dir
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    _set_global_seed(int(args.seed))

    tokenizer = CustomDeltaTokenizer(include_special_tokens=False)
    event_size = int(getattr(tokenizer, "event_size", 1))
    if event_size > 1:
        if int(args.seed_length) % event_size != 0:
            raise ValueError(
                f"seed_length must be divisible by event_size={event_size}; "
                f"got {int(args.seed_length)}"
            )
        if int(args.continuation_length) % event_size != 0:
            raise ValueError(
                "continuation_length must be divisible by event_size="
                f"{event_size}; got {int(args.continuation_length)}"
            )

    tokenizer_path = output_dir / "custom_tokenizer.json"
    tokenizer.save(str(tokenizer_path))

    min_required = int(args.max_sequence_length)
    manifest_input_path = Path(str(args.pretokenized_manifest)).expanduser()
    pretokenized_root = (
        Path(str(args.pretokenized_root)).expanduser()
        if str(args.pretokenized_root).strip()
        else None
    )

    manifest = _load_pretokenized_manifest(
        manifest_path=manifest_input_path,
        pretokenized_root=pretokenized_root,
        max_pieces=int(max(0, args.max_pieces)),
        min_required_tokens=min_required,
    )

    processed_dir = output_dir / "processed_pretokenized"
    processed_dir.mkdir(parents=True, exist_ok=True)
    manifest_out = processed_dir / "manifest.json"
    manifest_out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    train_manifest, val_manifest = _train_val_split(
        manifest=manifest,
        seed=int(args.seed),
        val_fraction=0.1,
    )

    data_cfg = DataConfig(
        tokenizer_path=str(tokenizer_path),
        processed_path=str(processed_dir),
        vocab_size=int(tokenizer.vocab_size),
        tokenization_strategy="custom_delta",
        seed_length=int(args.seed_length),
        continuation_length=int(args.continuation_length),
        max_sequence_length=int(args.max_sequence_length),
        use_continuous_time=True,
        time_feature_fallback_step_seconds=0.1,
    )

    probe_cfg = _build_train_config(
        args=args,
        checkpoint_dir=output_dir / "checkpoints" / "_probe",
        warmup_steps=1,
    )
    probe_train_loader, _ = _build_dataloaders(
        train_manifest=train_manifest,
        val_manifest=val_manifest,
        data_cfg=data_cfg,
        train_cfg=probe_cfg,
        seed=int(args.seed),
    )

    steps_per_epoch = max(
        1,
        math.ceil(
            len(probe_train_loader)
            / float(max(1, int(args.grad_accumulation_steps)))
        ),
    )
    total_steps = max(1, int(steps_per_epoch) * int(args.epochs))
    warmup_steps = (
        int(max(1, args.warmup_steps))
        if int(args.warmup_steps) > 0
        else int(max(1, round(float(args.warmup_ratio) * float(total_steps))))
    )

    model = VariantCModel(
        VariantCConfig(
            vocab_size=int(tokenizer.vocab_size),
            d_model=int(d_model),
            n_layers=int(n_layers),
            max_sequence_length=int(data_cfg.max_sequence_length),
            num_attention_heads=int(attn_heads),
            ffn_expansion=int(ffn_expansion),
        )
    )

    if torch.cuda.is_available():
        gpu_count = torch.cuda.device_count()
        gpu_names = [torch.cuda.get_device_name(i) for i in range(gpu_count)]
        LOGGER.info("Detected CUDA GPUs (%d): %s", gpu_count, gpu_names)
        if gpu_count > 1 and not bool(args.disable_data_parallel):
            LOGGER.info("Variant C will use DataParallel across available GPUs.")
            if int(args.batch_size) < int(gpu_count):
                LOGGER.warning(
                    "batch_size=%d is smaller than detected gpu_count=%d. "
                    "DataParallel will leave some GPUs idle. "
                    "Set --batch_size >= %d to utilize all GPUs.",
                    int(args.batch_size),
                    int(gpu_count),
                    int(gpu_count),
                )

    checkpoint_dir = output_dir / "checkpoints" / f"variant_c_{str(args.size_preset).lower()}"
    train_cfg = _build_train_config(
        args=args,
        checkpoint_dir=checkpoint_dir,
        warmup_steps=warmup_steps,
    )
    resume_checkpoint = _resolve_resume_checkpoint_arg(
        raw_value=str(args.resume_from_checkpoint),
        default_checkpoint_dir=checkpoint_dir,
    )

    seed_midi: Optional[Path]
    if str(args.seed_midi).strip():
        seed_midi = Path(str(args.seed_midi)).expanduser()
        if not seed_midi.exists():
            raise FileNotFoundError(f"seed_midi not found: {seed_midi.resolve()}")
    else:
        seed_midi = None

    LOGGER.info(
        "Variant C sub-100M setup: preset=%s target~%d | d_model=%d n_layers=%d heads=%d ffn_exp=%d",
        str(args.size_preset).lower(),
        int(preset["target_params"]),
        int(d_model),
        int(n_layers),
        int(attn_heads),
        int(ffn_expansion),
    )
    LOGGER.info(
        "Training setup: max_pieces=%d train=%d val=%d steps/epoch=%d total_steps=%d warmup=%d batch=%d grad_acc=%d",
        int(max(0, args.max_pieces)),
        len(train_manifest),
        len(val_manifest),
        int(steps_per_epoch),
        int(total_steps),
        int(warmup_steps),
        int(args.batch_size),
        int(args.grad_accumulation_steps),
    )
    if resume_checkpoint is not None:
        LOGGER.info(
            "Resume requested: checkpoint=%s mode=%s epochs=%d",
            str(resume_checkpoint.resolve()),
            str(args.resume_mode).lower(),
            int(args.epochs),
        )

    generation_out = (
        output_dir / "generated" / f"variant_c_{str(args.size_preset).lower()}.mid"
        if seed_midi is not None
        else None
    )
    result = _run_variant(
        variant_name="variant_c",
        model=model,
        tokenizer=tokenizer,
        data_cfg=data_cfg,
        train_cfg=train_cfg,
        train_manifest=train_manifest,
        val_manifest=val_manifest,
        seed_midi=seed_midi,
        output_midi_path=generation_out,
        generation_max_new_tokens=int(max(1, args.generation_max_new_tokens)),
        generation_continuation_seconds=float(
            max(1.0, args.generation_continuation_seconds)
        ),
        resume_from_checkpoint=resume_checkpoint,
        resume_mode=str(args.resume_mode).lower(),
    )

    payload: Dict[str, Any] = {
        "profile": f"variant_c_{str(args.size_preset).lower()}",
        "target_params": int(preset["target_params"]),
        "model_profile": {
            "d_model": int(d_model),
            "n_layers": int(n_layers),
            "num_attention_heads": int(attn_heads),
            "ffn_expansion": int(ffn_expansion),
            "max_sequence_length": int(args.max_sequence_length),
        },
        "training_profile": {
            "epochs": int(args.epochs),
            "batch_size": int(args.batch_size),
            "grad_accumulation_steps": int(args.grad_accumulation_steps),
            "learning_rate": float(args.learning_rate),
            "warmup_steps": int(warmup_steps),
            "steps_per_epoch": int(steps_per_epoch),
            "total_steps": int(total_steps),
            "max_pieces": int(max(0, args.max_pieces)),
            "min_lr_ratio": float(args.min_lr_ratio),
            "weight_decay": float(args.weight_decay),
            "label_smoothing": float(args.label_smoothing),
            "max_grad_norm": float(args.max_grad_norm),
            "num_workers": int(max(0, args.num_workers)),
            "log_every_n_steps": int(max(1, args.log_every_n_steps)),
            "generation_max_new_tokens": int(max(1, args.generation_max_new_tokens)),
            "generation_continuation_seconds": float(
                max(1.0, args.generation_continuation_seconds)
            ),
            "data_parallel_enabled": not bool(args.disable_data_parallel),
            "resume_mode": str(args.resume_mode).lower(),
            "resume_from_checkpoint": str(resume_checkpoint.resolve())
            if resume_checkpoint is not None
            else "",
        },
        "data": {
            "manifest_path": str(manifest_out.resolve()),
            "train_pieces": int(len(train_manifest)),
            "val_pieces": int(len(val_manifest)),
        },
        "result": result,
    }

    result_path = output_dir / f"variant_c_{str(args.size_preset).lower()}_result.json"
    result_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    print("Variant C sub-100M run complete")
    print(f"  preset: {str(args.size_preset).lower()}")
    print(f"  params: {int(result['params']):,} ({float(result['params']) / 1e6:.2f}M)")
    print(f"  result_json: {result_path.resolve()}")


if __name__ == "__main__":
    main()
