from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Optional

import torch

from config import DataConfig, TrainConfig
from data.tokenizer import CustomDeltaTokenizer
from model.variant_e import VariantEConfig, VariantEModel
from training.ablation_runner import (
    _build_dataloaders,
    _load_pretokenized_manifest,
    _run_variant,
    _set_global_seed,
    _train_val_split,
    _variant_backend_status,
)
from utils.logging_utils import get_project_logger


LOGGER = get_project_logger()


def _resolve_divisible_heads(width: int, requested_heads: int) -> int:
    heads = max(1, min(int(requested_heads), int(width)))
    while heads > 1 and (int(width) % heads) != 0:
        heads -= 1
    return max(1, heads)


def _build_train_config(
    *,
    args: argparse.Namespace,
    checkpoint_dir: Path,
    warmup_steps: int,
) -> TrainConfig:
    cfg = TrainConfig(
        batch_size=int(args.batch_size),
        grad_accumulation_steps=int(args.grad_accumulation_steps),
        learning_rate=float(args.learning_rate),
        lr_schedule="cosine",
        min_lr_ratio=float(args.min_lr_ratio),
        weight_decay=float(args.weight_decay),
        label_smoothing=float(args.label_smoothing),
        max_epochs=int(args.epochs),
        warmup_steps=int(max(1, warmup_steps)),
        max_grad_norm=float(args.max_grad_norm),
        save_every_n_epochs=int(max(1, args.save_every_n_epochs)),
        keep_every_n_epochs=int(max(1, args.keep_every_n_epochs)),
        max_checkpoints=int(max(1, args.max_checkpoints)),
        checkpoint_dir=str(checkpoint_dir),
        use_wandb=False,
        seed=int(args.seed),
        device="auto",
        val_generation_check=False,
    )
    setattr(cfg, "_force_num_workers", int(max(0, args.num_workers)))
    setattr(cfg, "_enable_data_parallel", bool(args.enable_data_parallel))
    setattr(cfg, "_allow_gdn_data_parallel", bool(args.allow_gdn_data_parallel))
    setattr(cfg, "_log_every_n_steps", int(max(1, args.log_every_n_steps)))
    return cfg


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train Variant E at ~150M params on pre-tokenized Godzilla NPZ data. "
            "This keeps architecture-ablation scripts separate from production runs."
        )
    )
    parser.add_argument(
        "--pretokenized_manifest",
        type=str,
        required=True,
        help="Path to manifest.json generated by scripts/tokenize_godzilla_local.py",
    )
    parser.add_argument(
        "--pretokenized_root",
        type=str,
        default="",
        help="Optional root to resolve relative npz paths from the manifest.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="outputs/variant_e_150m",
        help="Output root for checkpoints, model metadata, and optional generation.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--seed_length", type=int, default=512)
    parser.add_argument("--continuation_length", type=int, default=1536)
    parser.add_argument("--max_sequence_length", type=int, default=2048)
    parser.add_argument(
        "--max_pieces",
        type=int,
        default=0,
        help="Optional cap on total pieces from manifest (0 means full dataset).",
    )

    # 150M production profile (Variant E).
    parser.add_argument("--d_model", type=int, default=1344)
    parser.add_argument("--n_layers", type=int, default=17)
    parser.add_argument(
        "--attention_every_n_layers",
        type=int,
        default=2,
        help="Sparse attention anchor cadence for Variant E.",
    )
    parser.add_argument(
        "--gdn_inner_ratio",
        type=float,
        default=0.5,
        help="Inner width ratio for GDN blocks (inner_dim = d_model * ratio).",
    )
    parser.add_argument("--gdn_num_heads", type=int, default=4)
    parser.add_argument("--gqa_num_heads", type=int, default=8)
    parser.add_argument("--gqa_groups", type=int, default=4)

    # Quality-first training defaults for large runs.
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--grad_accumulation_steps", type=int, default=16)
    parser.add_argument("--learning_rate", type=float, default=2e-4)
    parser.add_argument("--min_lr_ratio", type=float, default=0.1)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--label_smoothing", type=float, default=0.1)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument(
        "--warmup_steps",
        type=int,
        default=0,
        help="If > 0, overrides warmup_ratio-based warmup.",
    )
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--log_every_n_steps", type=int, default=20)
    parser.add_argument("--save_every_n_epochs", type=int, default=5)
    parser.add_argument("--keep_every_n_epochs", type=int, default=10)
    parser.add_argument("--max_checkpoints", type=int, default=8)

    parser.add_argument(
        "--enable_data_parallel",
        action="store_true",
        help="Enable DataParallel for non-GDN fallback runs.",
    )
    parser.add_argument(
        "--allow_gdn_data_parallel",
        action="store_true",
        help="Override GDN safety guard and allow DataParallel with real GDN kernels.",
    )
    parser.add_argument(
        "--allow_fallback_gdn",
        action="store_true",
        help="Allow fallback GDN implementation. Recommended OFF for production-quality runs.",
    )

    parser.add_argument(
        "--seed_midi",
        type=str,
        default="",
        help="Optional seed MIDI for one post-training continuation export.",
    )
    parser.add_argument(
        "--generation_max_new_tokens",
        type=int,
        default=8192,
        help="Max tokens for optional post-train sample generation.",
    )
    parser.add_argument(
        "--generation_continuation_seconds",
        type=float,
        default=120.0,
        help="Target continuation length in seconds for optional sample export.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if int(args.d_model) <= 0 or int(args.n_layers) <= 0:
        raise ValueError("d_model and n_layers must be > 0")
    if int(args.seed_length) <= 0 or int(args.continuation_length) <= 0:
        raise ValueError("seed_length and continuation_length must be > 0")
    if int(args.max_sequence_length) <= 0:
        raise ValueError("max_sequence_length must be > 0")
    if int(args.seed_length) + int(args.continuation_length) != int(
        args.max_sequence_length
    ):
        raise ValueError(
            "seed_length + continuation_length must equal max_sequence_length "
            f"(got {int(args.seed_length) + int(args.continuation_length)} vs "
            f"{int(args.max_sequence_length)})"
        )

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    _set_global_seed(int(args.seed))

    tokenizer = CustomDeltaTokenizer(include_special_tokens=False)
    event_size = int(getattr(tokenizer, "event_size", 1))
    if event_size > 1:
        if int(args.seed_length) % event_size != 0:
            raise ValueError(
                f"seed_length must be divisible by event_size={event_size}; "
                f"got {int(args.seed_length)}"
            )
        if int(args.continuation_length) % event_size != 0:
            raise ValueError(
                "continuation_length must be divisible by event_size="
                f"{event_size}; got {int(args.continuation_length)}"
            )

    tokenizer_path = output_dir / "custom_tokenizer.json"
    tokenizer.save(str(tokenizer_path))

    min_required = int(args.max_sequence_length)
    manifest_input_path = Path(str(args.pretokenized_manifest)).expanduser()
    pretokenized_root = (
        Path(str(args.pretokenized_root)).expanduser()
        if str(args.pretokenized_root).strip()
        else None
    )

    manifest = _load_pretokenized_manifest(
        manifest_path=manifest_input_path,
        pretokenized_root=pretokenized_root,
        max_pieces=int(max(0, args.max_pieces)),
        min_required_tokens=min_required,
    )

    processed_dir = output_dir / "processed_pretokenized"
    processed_dir.mkdir(parents=True, exist_ok=True)
    manifest_out = processed_dir / "manifest.json"
    manifest_out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    train_manifest, val_manifest = _train_val_split(
        manifest=manifest,
        seed=int(args.seed),
        val_fraction=0.1,
    )

    data_cfg = DataConfig(
        tokenizer_path=str(tokenizer_path),
        processed_path=str(processed_dir),
        vocab_size=int(tokenizer.vocab_size),
        tokenization_strategy="custom_delta",
        seed_length=int(args.seed_length),
        continuation_length=int(args.continuation_length),
        max_sequence_length=int(args.max_sequence_length),
        use_continuous_time=True,
        time_feature_fallback_step_seconds=0.1,
    )

    probe_cfg = _build_train_config(
        args=args,
        checkpoint_dir=output_dir / "checkpoints" / "_probe",
        warmup_steps=1,
    )
    probe_train_loader, _ = _build_dataloaders(
        train_manifest=train_manifest,
        val_manifest=val_manifest,
        data_cfg=data_cfg,
        train_cfg=probe_cfg,
        seed=int(args.seed),
    )

    steps_per_epoch = max(
        1,
        math.ceil(
            len(probe_train_loader)
            / float(max(1, int(args.grad_accumulation_steps)))
        ),
    )
    total_steps = max(1, int(steps_per_epoch) * int(args.epochs))
    warmup_steps = (
        int(max(1, args.warmup_steps))
        if int(args.warmup_steps) > 0
        else int(max(1, round(float(args.warmup_ratio) * float(total_steps))))
    )

    gdn_inner_dim = max(128, int(round(float(args.d_model) * float(args.gdn_inner_ratio))))
    gdn_heads = _resolve_divisible_heads(gdn_inner_dim, int(args.gdn_num_heads))
    gqa_heads = _resolve_divisible_heads(int(args.d_model), int(args.gqa_num_heads))

    gqa_groups = max(1, int(args.gqa_groups))
    gqa_groups = min(gqa_groups, gqa_heads)
    while gqa_groups > 1 and (gqa_heads % gqa_groups) != 0:
        gqa_groups -= 1

    model = VariantEModel(
        VariantEConfig(
            vocab_size=int(tokenizer.vocab_size),
            d_model=int(args.d_model),
            n_layers=int(args.n_layers),
            max_sequence_length=int(data_cfg.max_sequence_length),
            gdn_inner_dim=int(gdn_inner_dim),
            gdn_num_heads=int(gdn_heads),
            gqa_num_heads=int(gqa_heads),
            gqa_groups=int(gqa_groups),
            attention_every_n_layers=int(max(1, args.attention_every_n_layers)),
        )
    )

    backend_status = _variant_backend_status(model)
    if backend_status.get("gdn_using_fallback", False) and not bool(args.allow_fallback_gdn):
        raise RuntimeError(
            "Variant E is using fallback GDN in this runtime. "
            "For production-quality 150M training, use real flash-linear-attention GDN kernels "
            "or pass --allow_fallback_gdn to run anyway."
        )

    if torch.cuda.is_available():
        gpu_count = torch.cuda.device_count()
        gpu_names = [torch.cuda.get_device_name(i) for i in range(gpu_count)]
        LOGGER.info("Detected CUDA GPUs (%d): %s", gpu_count, gpu_names)
        if (
            gpu_count > 1
            and not backend_status.get("gdn_using_fallback", False)
            and not bool(args.allow_gdn_data_parallel)
        ):
            LOGGER.warning(
                "Variant E with real GDN uses single-GPU mode by default due Triton replica instability. "
                "On Kaggle, prefer P100 over 2xT4 if you are not overriding DataParallel."
            )

    train_cfg = _build_train_config(
        args=args,
        checkpoint_dir=output_dir / "checkpoints" / "variant_e_150m",
        warmup_steps=warmup_steps,
    )

    seed_midi: Optional[Path]
    if str(args.seed_midi).strip():
        seed_midi = Path(str(args.seed_midi)).expanduser()
        if not seed_midi.exists():
            raise FileNotFoundError(f"seed_midi not found: {seed_midi.resolve()}")
    else:
        seed_midi = None

    LOGGER.info(
        "Variant E production setup: params~150M target | d_model=%d n_layers=%d "
        "gdn_inner_dim=%d gdn_heads=%d gqa_heads=%d gqa_groups=%d attn_every=%d",
        int(args.d_model),
        int(args.n_layers),
        int(gdn_inner_dim),
        int(gdn_heads),
        int(gqa_heads),
        int(gqa_groups),
        int(max(1, args.attention_every_n_layers)),
    )
    LOGGER.info(
        "Training setup: train=%d val=%d steps/epoch=%d total_steps=%d warmup=%d "
        "batch=%d grad_acc=%d",
        len(train_manifest),
        len(val_manifest),
        int(steps_per_epoch),
        int(total_steps),
        int(warmup_steps),
        int(args.batch_size),
        int(args.grad_accumulation_steps),
    )

    generation_out = (
        output_dir / "generated" / "variant_e_150m.mid" if seed_midi is not None else None
    )
    result = _run_variant(
        variant_name="variant_e",
        model=model,
        tokenizer=tokenizer,
        data_cfg=data_cfg,
        train_cfg=train_cfg,
        train_manifest=train_manifest,
        val_manifest=val_manifest,
        seed_midi=seed_midi,
        output_midi_path=generation_out,
        generation_max_new_tokens=int(max(1, args.generation_max_new_tokens)),
        generation_continuation_seconds=float(
            max(1.0, args.generation_continuation_seconds)
        ),
    )

    payload: Dict[str, Any] = {
        "profile": "variant_e_150m",
        "target_params": 150_000_000,
        "model_profile": {
            "d_model": int(args.d_model),
            "n_layers": int(args.n_layers),
            "attention_every_n_layers": int(max(1, args.attention_every_n_layers)),
            "gdn_inner_dim": int(gdn_inner_dim),
            "gdn_num_heads": int(gdn_heads),
            "gqa_num_heads": int(gqa_heads),
            "gqa_groups": int(gqa_groups),
            "max_sequence_length": int(args.max_sequence_length),
        },
        "training_profile": {
            "epochs": int(args.epochs),
            "batch_size": int(args.batch_size),
            "grad_accumulation_steps": int(args.grad_accumulation_steps),
            "learning_rate": float(args.learning_rate),
            "warmup_steps": int(warmup_steps),
            "steps_per_epoch": int(steps_per_epoch),
            "total_steps": int(total_steps),
            "min_lr_ratio": float(args.min_lr_ratio),
            "weight_decay": float(args.weight_decay),
            "label_smoothing": float(args.label_smoothing),
            "max_grad_norm": float(args.max_grad_norm),
            "num_workers": int(max(0, args.num_workers)),
            "log_every_n_steps": int(max(1, args.log_every_n_steps)),
            "generation_max_new_tokens": int(max(1, args.generation_max_new_tokens)),
            "generation_continuation_seconds": float(
                max(1.0, args.generation_continuation_seconds)
            ),
        },
        "backend_status": backend_status,
        "data": {
            "manifest_path": str(manifest_out.resolve()),
            "train_pieces": int(len(train_manifest)),
            "val_pieces": int(len(val_manifest)),
        },
        "result": result,
    }

    result_path = output_dir / "variant_e_150m_result.json"
    result_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    print("Variant E 150M run complete")
    print(f"  params: {int(result['params']):,} ({float(result['params']) / 1e6:.2f}M)")
    print(f"  result_json: {result_path.resolve()}")


if __name__ == "__main__":
    main()
